### ISSUE TITLE
Create Route Tool

### ISSUE THREAD

**Issue by jkreyling** [NJOGIS/NJRoadEditor#15] opened 2016-06-15 14:20 UTC
Interstate Ramp under symbol type is spelled wrong in the drop down of the create route tool.  When attempting to create an interstate ramp the tool will not work.

**Comment by EdFarrell** [comment] 2016-06-24 17:14
To clarify, the misspelling occurs in the New Segment tool. It is fixed. The fix has been commited and in the 3.1.1 release (in draft right now) as soon as the fix is confirmed. Please test and let me know if the problem is fixed Jason.

```
Traceback (most recent call last):
  File "<string>", line 2155, in execute
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\arcobjects\arcobjects.py", line 1096, in setValue
    return convertArcObjectToPythonObject(self._arc_object.SetValue(*gp_fixargs(args)))
RuntimeError: ERROR 999999: Error executing function.
The value type is incompatible with the field type. [SYMBOL_TYPE_ID]

Failed to execute (NewSegment).
```

**Closed as completed** 2016-06-27 12:59 UTC
Labels: bug
